hash-format = "sha256"

[[files]]
file = "config/lithium.properties"
hash = "4a005b99813a9dfb95b38a97c1de0e95221bd3c8f1a6a076df2ea9b5416fbc61"

[[files]]
file = "config/sodium-fingerprint.json"
hash = "381920cb97eaea1c21da0b9bdba69ea4e999eaa8849c363049d54d699a28664e"

[[files]]
file = "config/sodium-options.json"
hash = "706ae40fe0ef49027c07a05b731bf099b7ccf8e2a7c7c6c1d2fb192b95247402"

[[files]]
file = "config/voicechat/voicechat-client.properties"
hash = "e85ceea0a1fcd0e54e3ab9b6a2e95c67fd2e0a85885af0a3d2d4a419095c0650"

[[files]]
file = "config/voicechat/voicechat-server.properties"
hash = "5d6827441296c3e3df3e8692d867b051e50dd91291413969b2d0cf8c23f0b642"

[[files]]
file = "debug-profile.json"
hash = "4cd48e9a4baef4348d2f863ee3fe9e0ef523d291a07d0dd0c5a4db22dc5d7159"

[[files]]
file = "hotbar.nbt"
hash = "72e8580016668e078f50476fb6e7bdffdf6e419038711f4d592b4621757759eb"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "7467a101c890769c5d0796e1a4d646074ef8f96c9c1d2995dbb0f3972ea49916"
metafile = true

[[files]]
file = "mods/client-commands.pw.toml"
hash = "c78bcdcb1ac530f0cdfe0588155f27b5f573e4deb3bb87c18eb4096d53a8c84f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "c9babfbb0db58f9edfc38666af8ef4ce24fe0cd0594d3c421bb51410fb6c3fa2"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "ed9d0d5d4078c137900006321d35515cee46058b92df1128ea37cda3e5e1bb2b"
metafile = true

[[files]]
file = "mods/moonrise-opt.pw.toml"
hash = "6b496c6017d3256f203fa8bbfeab1aa0763122a66e9f7808801272b305b8b1a2"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "279ea1bb4b776be9176fe34416e2132e37abfce4483def54177091cc0f2faade"
metafile = true

[[files]]
file = "mods/wayfix.pw.toml"
hash = "2b1ba0449322c2563e58907a980c0243d7bb14e8c739d990b9dd341ea40298d6"
metafile = true

[[files]]
file = "options.txt"
hash = "6a7d48bc718f75d606e8e003ec12d52dc4a3423f6d087b79bd0af0f2e114bf7d"

[[files]]
file = "servers.dat"
hash = "24bc61ab85621ede172cbdc23457a10510f480e0df5ec73922c8afefb6b6dc4a"
